version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - ./docker/.database:/var/lib/mysql
    restart: always
    ports:
      - 3307:3306
    env_file: ./.env.local
  fpm:
    image: devilbox/php-fpm:7.2-prod
    volumes:
      - ./:/app
    restart: always
  nginx:
    image: nginx:1.16-alpine
    volumes:
      - ./:/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
    ports:
      - 8090:80
    depends_on:
      - fpm
      - db
  composer:
    image: composer:1.6
    volumes:
      - ./:/app
    restart: 'no'
    command: install --ignore-platform-reqs
    depends_on:
      - nginx