parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\EventListener\ExceptionListener:
        arguments:
            $environment: '%kernel.environment%'
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    App\Serializer\Normalizer\:
        resource: '%kernel.project_dir%/src/Serializer/Normalizer'
        tags: [serializer.normalizer]

    _instanceof:
        App\CommandBus\BaseHandler:
            tags:
                - { name: tactician.handler, typehints: true }